name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  scala:
    name: publish scala
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version: [3.2.1, 3.3.1]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - uses: jodersky/setup-mill@master
        with:
          mill-version: 0.10.12
      - name: assembly
        run: mill 'liga[2.12].assembly'
        env:
          SPARK_VERSION: ${{ matrix.spark-version }}
      - name: Rename out.jar to liga-sparkXYZ-assembly_2.12-version.jar
        run: cp ${{ github.workspace }}/out/liga/2.12/assembly.dest/out.jar ${JAR_PATH}
        env:
          SPARK_VERSION: ${{ matrix.spark-version }}
          REF_NAME: ${{ github.ref_name }}
          JAR_PATH: /tmp/liga-spark"${SPARK_VERSION//./}"-assembly_2.12-${REF_NAME//\//}.jar
      - name: Upload assembly
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          path: ${JAR_PATH}
        env:
          SPARK_VERSION: ${{ matrix.spark-version }}
          REF_NAME: ${{ github.ref_name }}
          JAR_PATH: /tmp/liga-spark"${SPARK_VERSION//./}"-assembly_2.12-${REF_NAME//\//}.jar
      - name: Release assembly
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: ${JAR_PATH}
        env:
          SPARK_VERSION: ${{ matrix.spark-version }}
          REF_NAME: ${{ github.ref_name }}
          JAR_PATH: /tmp/liga-spark"${SPARK_VERSION//./}"-assembly_2.12-${REF_NAME//\//}.jar
