name: publish

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  scala:
    name: publish scala
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spark-version: [3.2.1, 3.3.1]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: sbt-assembly-${{ hashFiles('**/build.sbt') }}
      - name: assembly
        run: sbt assembly
        env:
          SPARK_VERSION: ${{ matrix.spark-version }}
      - name: Upload assembly
          uses: actions/upload-artifact@v3
          if: ${{ !startsWith(github.ref, 'refs/tags/') }}
          with:
            path: ${{ github.workspace }}/target/scala-2.12/liga-*.jar
      - name: Release assembly
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: ${{ github.workspace }}/target/scala-2.12/liga-*.jar